[package]
name = "exifmanifest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exif = "0.0.1"
serde_json = "1.0.66"
walkdir = "2.3.1"
serde = { version = "1.0", features = ["derive"] }